#!/bin/bash
num=1
row=1
while [ $row -le 4 ]; do
for (( i=1; i<=$row; i++ )); do
echo -n "$num "
num=$((num+1))
done
echo ""
row=$((row+1))
done

OUTPUT
mlm@mlm-H81:~/Desktop/anandu/mca$ chmod +x numberseries.sh
mlm@mlm-H81:~/Desktop/anandu/mca$ ./numberseries.sh
1 
2 3 
4 5 6 
7 8 9 10
